
def dug(a):
    import turtle
    turtle.shape('turtle')
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
    turtle.right(15) 
    turtle.forward(a)
